spring.application.name=recetario-api

# Base de datos H2 en memoria (no requiere instalar nada)
spring.datasource.url=jdbc:h2:mem:recetariodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola de H2 (opcional): http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger UI: http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
